replicaCount: 1

image:
  repository: librarypal-books-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8001
  nodePort: 30003  # For Minikube access

db:
  user: root
  password: admin123
  host: librarypal-db-service
  name: library

resources: {}
